export const REQUEST_NEW_SPACE = "REQUEST_NEW_SPACE";
export const RECEIVE_NEW_SPACE = "RECEIVE_NEW_SPACE";
export const CLEAR_FIELD_SPACE = "CLEAR_FIELD_SPACE";
export const RECEIVE_GET_SPACE = "RECEIVE_GET_SPACE";
export const REQUEST_GET_SPACE = "REQUEST_GET_SPACE";
