export const REQUEST_GET_USERS = "REQUEST_GET_USERS";
export const RECEIVE_GET_USERS = "RECEIVE_GET_USERS";
export const REQUEST_USER_BY_ID = "REQUEST_USER_BY_ID";
export const RECEIVE_USER_BY_ID = "RECEIVE_USER_BY_ID";

export const REQUEST_UPDATE_PROFILE = "REQUEST_UPDATE_PROFILE";
export const RECEIVE_UPDATE_PROFILE = "RECEIVE_UPDATE_PROFILE";
export const CLEAR_UPDATE_STATUS = "CLEAR_UPDATE_STATUS";
